CREATE TABLE sbt.Ledger (
    Id  			BIGINT		NOT NULL	GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	Guid 			UUID 		NOT NULL	DEFAULT uuid_generate_v4(),
	TeamId  		BIGINT		NOT NULL    REFERENCES sbt.Team(Id),
	Description 	TEXT		NULL,	
	CreatedOn   	TIMESTAMP 	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    CreatedById     BIGINT     NOT NULL    REFERENCES sbt.User(Id),
	UpdatedOn   	TIMESTAMP 	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
    UpdatedById     BIGINT     NOT NULL    REFERENCES sbt.User(Id),
	IsDeleted   	BOOLEAN 	NOT NULL	DEFAULT FALSE
);

CREATE UNIQUE INDEX ledger_guid_idx on sbt.Ledger(Guid); 
